version: '2'

services:
  onestopshop_ux:
    build:
      context: .
      args: 
        NODE_ENV: production
    env_file:
      - ./.env.prod
    command: npm run build
    container_name: onestopshop_ux_prod

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile  
    ports:
      - "80:80"  
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount custom nginx.conf file
    depends_on:
      - onestopshop_ux